name: Org Policies - Projects

on:
  push:
    branches:
    - main

env:
  PROJECT: ${{ secrets.GCP_PROJECT }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '313.0.0'
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
     
  #  - name: Deploy
  #    run: |
        
