name: Org Policies

on:
  push:
    branches:
    - develop

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
     
    - name: Deploy
      run: chmod +x ./org-policies.sh; bash ./org-policies.sh
