name: Org Policies

on:
  push:
    branches:
    - main

env:
  PROJECT: alert-vista-291320
  REGION: us-east1

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '313.0.0'
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
     
    - name: Deploy
      run: |
        
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictVpnPeerIPs All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictVpcPeering All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.vmCanIpForward All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictSharedVpcSubnetworks All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictSharedVpcHostProjects All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictPartnerInterconnectUsage All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictProtocolForwardingCreationForTypes All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictDirectGoogleAccess All
        gcloud resource-manager org-policies allow --project alert-vista-291320 --quiet constraints/compute.restrictLoadBalancerCreationForTypes All
